[book]
title = "Caramel Manual"
description = "Caramel is a functional language for building type-safe, scalable, and maintainable applications. Read the manual to get started, learn how to call existing Erlang/Elixir code, learn how to contribute, or just to have a reference of the standard library."

language = "en"
multilingual = false

authors = ["Leandro Ostera"]

src = "src"

[output.html]
cname = "caramel.run"
google-analytics = "G-HVSX9MBNEJ"

default-theme = "ayu"
preferred-dark-theme = "ayu"

git-repository-url = "https://github.com/AbstractMachinesLab/caramel"
git-repository-icon = "fa-github"

