name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.1
        skip_test:
          - false

    env:
      SKIP_TEST: ${{ matrix.skip_test }}
      OCAML_VERSION: ${{ matrix.ocaml-version }}
      OS: ${{ matrix.os }}
      TARBALL: caramel-$${ github.ref }}-${{ matrix.os }}.tar.gz

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cached Infra
        uses: actions/cache@v2
        env:
          cache-name: cached-opam
        with:
          path: |
           ~/.opam
           _build
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.opam*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.ocaml-version }}-
            ${{ runner.os }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: Install dependencies
        run: opam exec -- make deps

      - name: Build project
        run: opam exec -- make build

      - name: Run tests
        run: opam exec -- make test

      - name: Check code formatting
        if: ${{ success() && startsWith(matrix.os, 'Linux') }}
        run: opam exec -- make fmt

      - name: Create draft release
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        run: |
          cp _build/install/bin/caramelc .
          tar czf ${{ env.TARBALL }} ./caramelc

      - name: Create draft release
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: create_draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release tarball
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
          asset_path: ${{ env.TARBALL }}
          asset_name: ${{ env.TARBALL }} 
          asset_content_type: application/zip
